# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-08-28T00:15:38+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Service(BaseModel):
    is_two_day_shipping: bool
    is_base_shipping_method: bool
    shipping_method_id: str
    cutoff: str
    max_delivery_date: str
    min_delivery_date: str
    shipping_method_short_description: str
    service_level_description: str


class ShippingOptions(BaseModel):
    availability_status: str
    loyalty_availability_status: str
    available_to_promise_quantity: float
    services: List[Service]


class Fulfillment(BaseModel):
    product_id: str
    is_out_of_stock_in_all_store_locations: bool
    shipping_options: ShippingOptions


class Product(BaseModel):
    __typename: str
    tcin: str
    fulfillment: Fulfillment


class Data(BaseModel):
    product: Product


class Model(BaseModel):
    data: Data
